// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF0SFz6euuS2-EV6YxVv3G2oF6xxkX_Gk',
    appId: '1:44848223246:web:611aedb76c95478da3185f',
    messagingSenderId: '44848223246',
    projectId: 'nisanapp-f727a',
    authDomain: 'nisanapp-f727a.firebaseapp.com',
    databaseURL: 'https://nisanapp-f727a-default-rtdb.firebaseio.com',
    storageBucket: 'nisanapp-f727a.firebasestorage.app',
    measurementId: 'G-M3J606TGFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc7Vh_Xfpja5VxkS2h3ZPb-R9t3t1gjL4',
    appId: '1:44848223246:android:6466d9c27db35e82a3185f',
    messagingSenderId: '44848223246',
    projectId: 'nisanapp-f727a',
    databaseURL: 'https://nisanapp-f727a-default-rtdb.firebaseio.com',
    storageBucket: 'nisanapp-f727a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFouVJgJ-NYXffxtAkgtsZqH81HT0ER0g',
    appId: '1:44848223246:ios:22cc6971120f6380a3185f',
    messagingSenderId: '44848223246',
    projectId: 'nisanapp-f727a',
    databaseURL: 'https://nisanapp-f727a-default-rtdb.firebaseio.com',
    storageBucket: 'nisanapp-f727a.firebasestorage.app',
    iosBundleId: 'com.example.hellome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFouVJgJ-NYXffxtAkgtsZqH81HT0ER0g',
    appId: '1:44848223246:ios:22cc6971120f6380a3185f',
    messagingSenderId: '44848223246',
    projectId: 'nisanapp-f727a',
    databaseURL: 'https://nisanapp-f727a-default-rtdb.firebaseio.com',
    storageBucket: 'nisanapp-f727a.firebasestorage.app',
    iosBundleId: 'com.example.hellome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF0SFz6euuS2-EV6YxVv3G2oF6xxkX_Gk',
    appId: '1:44848223246:web:7fa5985a4cfca47ca3185f',
    messagingSenderId: '44848223246',
    projectId: 'nisanapp-f727a',
    authDomain: 'nisanapp-f727a.firebaseapp.com',
    databaseURL: 'https://nisanapp-f727a-default-rtdb.firebaseio.com',
    storageBucket: 'nisanapp-f727a.firebasestorage.app',
    measurementId: 'G-Y2E1BN6S60',
  );
}
